language: php

php:
  - 7.2

before_script:
  - composer install --prefer-source --no-interaction --dev --optimize-autoloader

script: vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration phpunit.xml
